# Generated by Django 2.2.7 on 2023-05-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmi', models.CharField(max_length=20)),
                ('meter_serial_number', models.CharField(max_length=20)),
                ('reading_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reading_date_time', models.DateTimeField()),
                ('flow_file_name', models.CharField(max_length=32)),
            ],
        ),
    ]
